apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-data-volume
  labels:
    io.kompose.service: mysql-database-data-volume
spec:
  storageClassName: standard   # Updated to use standard StorageClass for GCP
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
